version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: validator
    main: ./cmd/validator
    binary: dtvn-validator
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
      - -X main.BuiltBy=goreleaser

  - id: simulator
    main: ./cmd/simulator
    binary: dtvn-simulator
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
      - -X main.BuiltBy=goreleaser

archives:
  - id: dtvn
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - USER_GUIDE.md
      - QUICKSTART.md
      - LICENSE
      - config/validator.yaml

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Dependency Updates'
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: Hetti219
    name: DTVN
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## DTVN Release {{.Version}}

    Distributed Ticket Validation Network - A Byzantine Fault-Tolerant, peer-to-peer ticket validation system.

    ### Installation

    Download the appropriate binary for your platform below.

    ### Docker

    ```bash
    docker pull ghcr.io/hetti219/dtvn:{{.Version}}
    ```

  footer: |
    ### Full Changelog

    See all changes at: https://github.com/Hetti219/DTVN/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    **Verification**: All binaries are signed with Cosign and include SBOMs for supply chain security.

sboms:
  - id: archive
    artifacts: archive
    documents:
      - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.json"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    signature: "${artifact}.sig"
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes"
    artifacts: all
    output: true

announce:
  skip: true
