// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/messages.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TicketOperation defines the operation type
type TicketOperation int32

const (
	TicketOperation_VALIDATE TicketOperation = 0
	TicketOperation_CONSUME  TicketOperation = 1
	TicketOperation_DISPUTE  TicketOperation = 2
	TicketOperation_QUERY    TicketOperation = 3
)

// Enum value maps for TicketOperation.
var (
	TicketOperation_name = map[int32]string{
		0: "VALIDATE",
		1: "CONSUME",
		2: "DISPUTE",
		3: "QUERY",
	}
	TicketOperation_value = map[string]int32{
		"VALIDATE": 0,
		"CONSUME":  1,
		"DISPUTE":  2,
		"QUERY":    3,
	}
)

func (x TicketOperation) Enum() *TicketOperation {
	p := new(TicketOperation)
	*p = x
	return p
}

func (x TicketOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[0].Descriptor()
}

func (TicketOperation) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[0]
}

func (x TicketOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketOperation.Descriptor instead.
func (TicketOperation) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

// State enum for ticket states
type State int32

const (
	State_ISSUED    State = 0
	State_PENDING   State = 1
	State_VALIDATED State = 2
	State_CONSUMED  State = 3
	State_DISPUTED  State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "ISSUED",
		1: "PENDING",
		2: "VALIDATED",
		3: "CONSUMED",
		4: "DISPUTED",
	}
	State_value = map[string]int32{
		"ISSUED":    0,
		"PENDING":   1,
		"VALIDATED": 2,
		"CONSUMED":  3,
		"DISPUTED":  4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

type ValidatorMessage_Type int32

const (
	ValidatorMessage_PRE_PREPARE         ValidatorMessage_Type = 0
	ValidatorMessage_PREPARE             ValidatorMessage_Type = 1
	ValidatorMessage_COMMIT              ValidatorMessage_Type = 2
	ValidatorMessage_VIEW_CHANGE         ValidatorMessage_Type = 3
	ValidatorMessage_CHECKPOINT          ValidatorMessage_Type = 4
	ValidatorMessage_STATE_UPDATE        ValidatorMessage_Type = 5
	ValidatorMessage_HEARTBEAT           ValidatorMessage_Type = 6
	ValidatorMessage_CLIENT_REQUEST      ValidatorMessage_Type = 7
	ValidatorMessage_STATE_SYNC_REQUEST  ValidatorMessage_Type = 8
	ValidatorMessage_STATE_SYNC_RESPONSE ValidatorMessage_Type = 9
)

// Enum value maps for ValidatorMessage_Type.
var (
	ValidatorMessage_Type_name = map[int32]string{
		0: "PRE_PREPARE",
		1: "PREPARE",
		2: "COMMIT",
		3: "VIEW_CHANGE",
		4: "CHECKPOINT",
		5: "STATE_UPDATE",
		6: "HEARTBEAT",
		7: "CLIENT_REQUEST",
		8: "STATE_SYNC_REQUEST",
		9: "STATE_SYNC_RESPONSE",
	}
	ValidatorMessage_Type_value = map[string]int32{
		"PRE_PREPARE":         0,
		"PREPARE":             1,
		"COMMIT":              2,
		"VIEW_CHANGE":         3,
		"CHECKPOINT":          4,
		"STATE_UPDATE":        5,
		"HEARTBEAT":           6,
		"CLIENT_REQUEST":      7,
		"STATE_SYNC_REQUEST":  8,
		"STATE_SYNC_RESPONSE": 9,
	}
)

func (x ValidatorMessage_Type) Enum() *ValidatorMessage_Type {
	p := new(ValidatorMessage_Type)
	*p = x
	return p
}

func (x ValidatorMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidatorMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[2].Descriptor()
}

func (ValidatorMessage_Type) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[2]
}

func (x ValidatorMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidatorMessage_Type.Descriptor instead.
func (ValidatorMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0, 0}
}

// ValidatorMessage is the main message type for communication between validators
type ValidatorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ValidatorMessage_Type  `protobuf:"varint,1,opt,name=type,proto3,enum=validator.ValidatorMessage_Type" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId      string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorMessage) Reset() {
	*x = ValidatorMessage{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorMessage) ProtoMessage() {}

func (x *ValidatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorMessage.ProtoReflect.Descriptor instead.
func (*ValidatorMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorMessage) GetType() ValidatorMessage_Type {
	if x != nil {
		return x.Type
	}
	return ValidatorMessage_PRE_PREPARE
}

func (x *ValidatorMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ValidatorMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ValidatorMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ValidatorMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

// PrePrepare message from primary/leader node
type PrePrepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Request       *Request               `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepare) Reset() {
	*x = PrePrepare{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepare) ProtoMessage() {}

func (x *PrePrepare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepare.ProtoReflect.Descriptor instead.
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PrePrepare) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrePrepare) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PrePrepare) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrePrepare) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Prepare message from replica nodes
type Prepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Prepare) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Prepare) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Prepare) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Prepare) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Commit message from replica nodes
type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int64                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Commit) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Commit) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Commit) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Commit) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// ViewChange message for leader election
type ViewChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewView       int64                  `protobuf:"varint,1,opt,name=new_view,json=newView,proto3" json:"new_view,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Prepared      []*PreparedProof       `protobuf:"bytes,3,rep,name=prepared,proto3" json:"prepared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewChange) Reset() {
	*x = ViewChange{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChange) ProtoMessage() {}

func (x *ViewChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChange.ProtoReflect.Descriptor instead.
func (*ViewChange) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ViewChange) GetNewView() int64 {
	if x != nil {
		return x.NewView
	}
	return 0
}

func (x *ViewChange) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ViewChange) GetPrepared() []*PreparedProof {
	if x != nil {
		return x.Prepared
	}
	return nil
}

// PreparedProof contains proof of preparation
type PreparedProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	View          int64                  `protobuf:"varint,3,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparedProof) Reset() {
	*x = PreparedProof{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedProof) ProtoMessage() {}

func (x *PreparedProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedProof.ProtoReflect.Descriptor instead.
func (*PreparedProof) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PreparedProof) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreparedProof) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PreparedProof) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

// Checkpoint message for state snapshots
type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	StateDigest   []byte                 `protobuf:"bytes,2,opt,name=state_digest,json=stateDigest,proto3" json:"state_digest,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Checkpoint) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Checkpoint) GetStateDigest() []byte {
	if x != nil {
		return x.StateDigest
	}
	return nil
}

func (x *Checkpoint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Checkpoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StateUpdate message for gossip protocol
type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketState         `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *StateUpdate) GetTickets() []*TicketState {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *StateUpdate) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *StateUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// VectorClock for causality tracking
type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clocks        map[string]uint64      `protobuf:"bytes,1,rep,name=clocks,proto3" json:"clocks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *VectorClock) GetClocks() map[string]uint64 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

// Request represents a ticket validation request
type Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TicketId        string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Operation       TicketOperation        `protobuf:"varint,3,opt,name=operation,proto3,enum=validator.TicketOperation" json:"operation,omitempty"`
	TicketData      []byte                 `protobuf:"bytes,4,opt,name=ticket_data,json=ticketData,proto3" json:"ticket_data,omitempty"`
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientSignature []byte                 `protobuf:"bytes,6,opt,name=client_signature,json=clientSignature,proto3" json:"client_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Request) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Request) GetOperation() TicketOperation {
	if x != nil {
		return x.Operation
	}
	return TicketOperation_VALIDATE
}

func (x *Request) GetTicketData() []byte {
	if x != nil {
		return x.TicketData
	}
	return nil
}

func (x *Request) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Request) GetClientSignature() []byte {
	if x != nil {
		return x.ClientSignature
	}
	return nil
}

// TicketState represents the state of a ticket
type TicketState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=validator.State" json:"state,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	ValidatorId   string                 `protobuf:"bytes,4,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,5,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketState) Reset() {
	*x = TicketState{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketState) ProtoMessage() {}

func (x *TicketState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketState.ProtoReflect.Descriptor instead.
func (*TicketState) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *TicketState) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketState) GetState() State {
	if x != nil {
		return x.State
	}
	return State_ISSUED
}

func (x *TicketState) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *TicketState) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *TicketState) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *TicketState) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GossipMessage for peer-to-peer dissemination
type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	SeenBy        []string               `protobuf:"bytes,4,rep,name=seen_by,json=seenBy,proto3" json:"seen_by,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *GossipMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GossipMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GossipMessage) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GossipMessage) GetSeenBy() []string {
	if x != nil {
		return x.SeenBy
	}
	return nil
}

func (x *GossipMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PeerInfo for peer discovery
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IsValidator   bool                   `protobuf:"varint,4,opt,name=is_validator,json=isValidator,proto3" json:"is_validator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetIsValidator() bool {
	if x != nil {
		return x.IsValidator
	}
	return false
}

// HealthCheck message
type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Stats         *NetworkStats          `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheck) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthCheck) GetStats() *NetworkStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// NodeStatus represents current node status
type NodeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy       bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	CurrentView     int64                  `protobuf:"varint,2,opt,name=current_view,json=currentView,proto3" json:"current_view,omitempty"`
	CurrentSequence int64                  `protobuf:"varint,3,opt,name=current_sequence,json=currentSequence,proto3" json:"current_sequence,omitempty"`
	ConnectedPeers  int32                  `protobuf:"varint,4,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`
	Role            string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *NodeStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *NodeStatus) GetCurrentView() int64 {
	if x != nil {
		return x.CurrentView
	}
	return 0
}

func (x *NodeStatus) GetCurrentSequence() int64 {
	if x != nil {
		return x.CurrentSequence
	}
	return 0
}

func (x *NodeStatus) GetConnectedPeers() int32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

func (x *NodeStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// NetworkStats for monitoring
type NetworkStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessagesSent     int64                  `protobuf:"varint,1,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived int64                  `protobuf:"varint,2,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	ConsensusRounds  int64                  `protobuf:"varint,3,opt,name=consensus_rounds,json=consensusRounds,proto3" json:"consensus_rounds,omitempty"`
	FailedConsensus  int64                  `protobuf:"varint,4,opt,name=failed_consensus,json=failedConsensus,proto3" json:"failed_consensus,omitempty"`
	AvgLatencyMs     float64                `protobuf:"fixed64,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_proto_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkStats) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *NetworkStats) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

func (x *NetworkStats) GetConsensusRounds() int64 {
	if x != nil {
		return x.ConsensusRounds
	}
	return 0
}

func (x *NetworkStats) GetFailedConsensus() int64 {
	if x != nil {
		return x.FailedConsensus
	}
	return 0
}

func (x *NetworkStats) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

// StateSyncRequest message for requesting state from peers
type StateSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	LastSequence  int64                  `protobuf:"varint,2,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"` // Last sequence number the requester has
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSyncRequest) Reset() {
	*x = StateSyncRequest{}
	mi := &file_proto_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSyncRequest) ProtoMessage() {}

func (x *StateSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSyncRequest.ProtoReflect.Descriptor instead.
func (*StateSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{16}
}

func (x *StateSyncRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *StateSyncRequest) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

func (x *StateSyncRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StateSyncResponse message for responding to state sync requests
type StateSyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResponderId      string                 `protobuf:"bytes,1,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	CurrentSequence  int64                  `protobuf:"varint,2,opt,name=current_sequence,json=currentSequence,proto3" json:"current_sequence,omitempty"`
	CurrentView      int64                  `protobuf:"varint,3,opt,name=current_view,json=currentView,proto3" json:"current_view,omitempty"`
	ValidatedTickets []*TicketState         `protobuf:"bytes,4,rep,name=validated_tickets,json=validatedTickets,proto3" json:"validated_tickets,omitempty"`
	ConsensusLog     []string               `protobuf:"bytes,5,rep,name=consensus_log,json=consensusLog,proto3" json:"consensus_log,omitempty"` // Simplified consensus log (ticket IDs)
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StateSyncResponse) Reset() {
	*x = StateSyncResponse{}
	mi := &file_proto_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSyncResponse) ProtoMessage() {}

func (x *StateSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSyncResponse.ProtoReflect.Descriptor instead.
func (*StateSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{17}
}

func (x *StateSyncResponse) GetResponderId() string {
	if x != nil {
		return x.ResponderId
	}
	return ""
}

func (x *StateSyncResponse) GetCurrentSequence() int64 {
	if x != nil {
		return x.CurrentSequence
	}
	return 0
}

func (x *StateSyncResponse) GetCurrentView() int64 {
	if x != nil {
		return x.CurrentView
	}
	return 0
}

func (x *StateSyncResponse) GetValidatedTickets() []*TicketState {
	if x != nil {
		return x.ValidatedTickets
	}
	return nil
}

func (x *StateSyncResponse) GetConsensusLog() []string {
	if x != nil {
		return x.ConsensusLog
	}
	return nil
}

func (x *StateSyncResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\tvalidator\"\xf5\x02\n" +
	"\x10ValidatorMessage\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .validator.ValidatorMessage.TypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\"\xb7\x01\n" +
	"\x04Type\x12\x0f\n" +
	"\vPRE_PREPARE\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x02\x12\x0f\n" +
	"\vVIEW_CHANGE\x10\x03\x12\x0e\n" +
	"\n" +
	"CHECKPOINT\x10\x04\x12\x10\n" +
	"\fSTATE_UPDATE\x10\x05\x12\r\n" +
	"\tHEARTBEAT\x10\x06\x12\x12\n" +
	"\x0eCLIENT_REQUEST\x10\a\x12\x16\n" +
	"\x12STATE_SYNC_REQUEST\x10\b\x12\x17\n" +
	"\x13STATE_SYNC_RESPONSE\x10\t\"\x82\x01\n" +
	"\n" +
	"PrePrepare\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12,\n" +
	"\arequest\x18\x04 \x01(\v2\x12.validator.RequestR\arequest\"j\n" +
	"\aPrepare\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"i\n" +
	"\x06Commit\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x03R\x04view\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"v\n" +
	"\n" +
	"ViewChange\x12\x19\n" +
	"\bnew_view\x18\x01 \x01(\x03R\anewView\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x124\n" +
	"\bprepared\x18\x03 \x03(\v2\x18.validator.PreparedProofR\bprepared\"W\n" +
	"\rPreparedProof\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x12\n" +
	"\x04view\x18\x03 \x01(\x03R\x04view\"\x82\x01\n" +
	"\n" +
	"Checkpoint\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12!\n" +
	"\fstate_digest\x18\x02 \x01(\fR\vstateDigest\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x93\x01\n" +
	"\vStateUpdate\x120\n" +
	"\atickets\x18\x01 \x03(\v2\x16.validator.TicketStateR\atickets\x129\n" +
	"\fvector_clock\x18\x02 \x01(\v2\x16.validator.VectorClockR\vvectorClock\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\x84\x01\n" +
	"\vVectorClock\x12:\n" +
	"\x06clocks\x18\x01 \x03(\v2\".validator.VectorClock.ClocksEntryR\x06clocks\x1a9\n" +
	"\vClocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xe9\x01\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x128\n" +
	"\toperation\x18\x03 \x01(\x0e2\x1a.validator.TicketOperationR\toperation\x12\x1f\n" +
	"\vticket_data\x18\x04 \x01(\fR\n" +
	"ticketData\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10client_signature\x18\x06 \x01(\fR\x0fclientSignature\"\xef\x01\n" +
	"\vTicketState\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12&\n" +
	"\x05state\x18\x02 \x01(\x0e2\x10.validator.StateR\x05state\x12!\n" +
	"\flast_updated\x18\x03 \x01(\x03R\vlastUpdated\x12!\n" +
	"\fvalidator_id\x18\x04 \x01(\tR\vvalidatorId\x129\n" +
	"\fvector_clock\x18\x05 \x01(\v2\x16.validator.VectorClockR\vvectorClock\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\"\x91\x01\n" +
	"\rGossipMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\x12\x17\n" +
	"\aseen_by\x18\x04 \x03(\tR\x06seenBy\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x81\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\x12!\n" +
	"\fis_validator\x18\x04 \x01(\bR\visValidator\"\xa2\x01\n" +
	"\vHealthCheck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x06status\x18\x03 \x01(\v2\x15.validator.NodeStatusR\x06status\x12-\n" +
	"\x05stats\x18\x04 \x01(\v2\x17.validator.NetworkStatsR\x05stats\"\xb6\x01\n" +
	"\n" +
	"NodeStatus\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12!\n" +
	"\fcurrent_view\x18\x02 \x01(\x03R\vcurrentView\x12)\n" +
	"\x10current_sequence\x18\x03 \x01(\x03R\x0fcurrentSequence\x12'\n" +
	"\x0fconnected_peers\x18\x04 \x01(\x05R\x0econnectedPeers\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\xdc\x01\n" +
	"\fNetworkStats\x12#\n" +
	"\rmessages_sent\x18\x01 \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\x02 \x01(\x03R\x10messagesReceived\x12)\n" +
	"\x10consensus_rounds\x18\x03 \x01(\x03R\x0fconsensusRounds\x12)\n" +
	"\x10failed_consensus\x18\x04 \x01(\x03R\x0ffailedConsensus\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x01R\favgLatencyMs\"x\n" +
	"\x10StateSyncRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12#\n" +
	"\rlast_sequence\x18\x02 \x01(\x03R\flastSequence\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x8c\x02\n" +
	"\x11StateSyncResponse\x12!\n" +
	"\fresponder_id\x18\x01 \x01(\tR\vresponderId\x12)\n" +
	"\x10current_sequence\x18\x02 \x01(\x03R\x0fcurrentSequence\x12!\n" +
	"\fcurrent_view\x18\x03 \x01(\x03R\vcurrentView\x12C\n" +
	"\x11validated_tickets\x18\x04 \x03(\v2\x16.validator.TicketStateR\x10validatedTickets\x12#\n" +
	"\rconsensus_log\x18\x05 \x03(\tR\fconsensusLog\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp*D\n" +
	"\x0fTicketOperation\x12\f\n" +
	"\bVALIDATE\x10\x00\x12\v\n" +
	"\aCONSUME\x10\x01\x12\v\n" +
	"\aDISPUTE\x10\x02\x12\t\n" +
	"\x05QUERY\x10\x03*K\n" +
	"\x05State\x12\n" +
	"\n" +
	"\x06ISSUED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tVALIDATED\x10\x02\x12\f\n" +
	"\bCONSUMED\x10\x03\x12\f\n" +
	"\bDISPUTED\x10\x04B9Z7github.com/Hetti219/DTVN/protob\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_messages_proto_goTypes = []any{
	(TicketOperation)(0),       // 0: validator.TicketOperation
	(State)(0),                 // 1: validator.State
	(ValidatorMessage_Type)(0), // 2: validator.ValidatorMessage.Type
	(*ValidatorMessage)(nil),   // 3: validator.ValidatorMessage
	(*PrePrepare)(nil),         // 4: validator.PrePrepare
	(*Prepare)(nil),            // 5: validator.Prepare
	(*Commit)(nil),             // 6: validator.Commit
	(*ViewChange)(nil),         // 7: validator.ViewChange
	(*PreparedProof)(nil),      // 8: validator.PreparedProof
	(*Checkpoint)(nil),         // 9: validator.Checkpoint
	(*StateUpdate)(nil),        // 10: validator.StateUpdate
	(*VectorClock)(nil),        // 11: validator.VectorClock
	(*Request)(nil),            // 12: validator.Request
	(*TicketState)(nil),        // 13: validator.TicketState
	(*GossipMessage)(nil),      // 14: validator.GossipMessage
	(*PeerInfo)(nil),           // 15: validator.PeerInfo
	(*HealthCheck)(nil),        // 16: validator.HealthCheck
	(*NodeStatus)(nil),         // 17: validator.NodeStatus
	(*NetworkStats)(nil),       // 18: validator.NetworkStats
	(*StateSyncRequest)(nil),   // 19: validator.StateSyncRequest
	(*StateSyncResponse)(nil),  // 20: validator.StateSyncResponse
	nil,                        // 21: validator.VectorClock.ClocksEntry
}
var file_proto_messages_proto_depIdxs = []int32{
	2,  // 0: validator.ValidatorMessage.type:type_name -> validator.ValidatorMessage.Type
	12, // 1: validator.PrePrepare.request:type_name -> validator.Request
	8,  // 2: validator.ViewChange.prepared:type_name -> validator.PreparedProof
	13, // 3: validator.StateUpdate.tickets:type_name -> validator.TicketState
	11, // 4: validator.StateUpdate.vector_clock:type_name -> validator.VectorClock
	21, // 5: validator.VectorClock.clocks:type_name -> validator.VectorClock.ClocksEntry
	0,  // 6: validator.Request.operation:type_name -> validator.TicketOperation
	1,  // 7: validator.TicketState.state:type_name -> validator.State
	11, // 8: validator.TicketState.vector_clock:type_name -> validator.VectorClock
	17, // 9: validator.HealthCheck.status:type_name -> validator.NodeStatus
	18, // 10: validator.HealthCheck.stats:type_name -> validator.NetworkStats
	13, // 11: validator.StateSyncResponse.validated_tickets:type_name -> validator.TicketState
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		EnumInfos:         file_proto_messages_proto_enumTypes,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
